### PR TITLE
PR - feat(data): add reviewed programs

### PR DESCRIPTION
**Pull request by pierrecamilleri**
cf https://github.com/orgs/betagouv/projects/54/views/3?pane=issue&itemId=36729073

### CODE REVIEW

**Comment by JulienParis** [comment]
Tests are failing due to the additional property “durée de l'accompagnement” (pending PR #154)

I guess there would be two options to merge this PR while passing the tests : 
- either pulling the main and/or preprod branch to this branch before merging (so to include the hot fix “additionalProperties: true”
- Or first merging #154 to preprod, then pulling preprod to this branch to avoid further conflicts

**Comment by JulienParis** [comment]
Also another question :

If there is no question track storing any value or key for “entreprise . code NAF” (w/ the rule consisting in “une de ces conditions”) how would publicodes would react ?

**Comment by pierrecamilleri** [comment]
> Tests are failing due to the additional property “durée de l'accompagnement” (pending PR #154)

Yes I need to rebase the branch after merging #156.

> If there is no question track storing any value or key for “entreprise . code NAF” (w/ the rule consisting in “une de ces conditions”) how would publicodes would react ?

A rule with missing data evaluates to `undefined`, and since the hotfix #151, publicodes keeps the programs which eligibility conditions evaluate to `undefined`, i.e. if we don't now, we keep the program. (It was failing before, but as we do not gather the same data in the two questionnaire tracks I had to change the behavior)

**Comment by JulienParis** [comment]
@pierrecamilleri Dans le but d'éviter au maximum des conflits de merge entre branches entre #147 et #155 (et uniquement dans le cadre de ces 2 PR), je te propose de ne pas garder dans cette branche les modifs relatives à `trackGoals.ts`. On pourra dédier une PR uniquement à l'intégration des nouveaux champs et des nouvelles conditions qui vont apparaître (en raison de tous les nouveaux dispositifs en yaml et des modifs sur `interface.yaml`) pour mettre à jour les questions et le filtrage côté front

**Comment by JulienParis** [comment]
@pierrecamilleri si tout te semble ok sur cette PR - et si tu n'en as plus l'usage - je pense que tu peux effacer cette branche (histoire de garder juste ce qui nous est utile dans notre liste de branches)

**Pull request merged**
